{
    "a": [
        "Alana",
        "Amanda",
        "Alice",
        "Ariana",
        "Addison",
        "Alexandra",
        "Anna",
        "Audrey",
        "Angel",
        "Amber",
        "Aurora",
        "Aaliyah",
        "Amelia",
        "Adrianna",
        "Ashley",
        "Abigail",
        "Ava",
        "Aisha",
    ],
    "b": [
        "Blossom",
        "Bella",
        "Brenda",
        "Britney",
        "Bonnie",
        "Brooklyn",
        "Bianca",
        "Brianna",
        "Bailey",
        "Bryn",
        "Bethany",
        "Betsy",
        "Barbara",
        "Brittany",
        "Baylee",
        "Beatrice",
    ],
    "c": [
        "Cecilia",
        "Charlotte",
        "Catherine",
        "Carly",
        "Christina",
        "Camila",
        "Clara",
        "Chelsea",
        "Celeste",
        "Carrie",
        "Cynthia",
        "Cassandra",
        "Crystal",
        "Cadence",
        "Caroline",
        "Chloe",
        "Courtney",
        "Cindy",
    ],
    "d": [
        "Dakota",
        "Diana",
        "Daisy",
        "Destiny",
        "Donna",
        "Doris",
        "Danielle",
        "Darlene",
        "Daphne",
        "Deborah",
        "Delilah",
        "Daniela",
        "Demi",
    ],
    "e": [
        "Eloise",
        "Emerald",
        "Emily",
        "Emma",
        "Eva",
        "Ella",
        "Erica",
        "Esther",
        "Eleanor",
        "Erin",
        "Elizabeth",
        "Eden",
        "Elise",
        "Evelyn",
        "Elena",
    ],
    "f": [
        "Fiona",
        "Frances",
        "Felicia",
        "Francesca",
        "Felicity",
        "Frida",
        "Farrah",
        "Florence",
        "Faith",
        "Fern",
        "Fernanda",
        "Fatima",
    ],
    "g": [
        "Gina",
        "Gabrielle",
        "Genevieve",
        "Grace",
        "Gwen",
        "Giselle",
        "Georgia",
        "Gretchen",
        "Gemma",
        "Gloria",
        "Gigi",
    ],
    "h": [
        "Hailey",
        "Haley",
        "Hilda",
        "Heidi",
        "Heather",
        "Hazel",
        "Hannah",
        "Hope",
        "Helen",
        "Harper",
        "Harmony",
        "Harriet"
        "Hilary",
        "Holly",
    ],
    "i": [
        "India",
        "Indigo",
        "Irene",
        "Isabella",
        "Isabel",
        "Imogen",
        "Iris",
        "Ingrid",
        "Ivy",
        "Isla",
    ],
    "j": [
        "Jessica",
        "Jane",
        "Julia",
        "Jamie",
        "Judith",
        "Jocelyn",
        "Joy",
        "Jordan",
        "Janet",
        "Jade",
        "Josephine",
        "Jasmine",
        "Jennifer",
        "Jewel",
        "Jenna",
    ],
    "k": [
        "Kelsey",
        "Kimberly",
        "Kendra",
        "Kristen",
        "Kara",
        "Kylie",
        "Katie",
        "Kelly",
        "Kassandra",
        "Katherine",
        "Karen",
        "Karina",
        "Kira",
        "Kiana",
        "Kathleen",
    ],
    "l": [
        "Lydia",
        "Lauren",
        "Lindsay",
        "Luna",
        "Layla",
        "Lucy",
        "Leslie",
        "Lila",
        "Lily",
        "Leah",
        "Lisa",
        "Laura",
        "Lola",
        "Lillian",
        "Lorna",
    ],
    "m": [
        "Melody",
        "Mia",
        "Madison",
        "Maureen",
        "Melissa",
        "Mary",
        "Melanie",
        "Michelle",
        "Maya",
        "Madeline",
        "Morgan",
        "Maria",
        "Mackenzie",
        "Mindy",
        "Margaret",
    ],
    "n": [
        "Naomi",
        "Nancy",
        "Nora",
        "Natalia",
        "Nicole",
        "Natalie",
        "Nadia",
        "Nina",
        "Nia",
        "Natasha",
    ],
    "o": ["Olivia", "Ophelia", "Oprah", "Olive", "Octavia", "Opal"],
    "p": [
        "Paige",
        "Penny",
        "Patricia",
        "Paula",
        "Pearl",
        "Polly",
        "Phoebe",
        "Pamela",
        "Penelope",
        "Poppy",
        "Priscilla",
    ],
    "q": ["Quorra", "Quinn", "Quincy", "Queenie", "Quiana"],
    "r": [
        "Rowan",
        "Robin",
        "Rita",
        "Ruth",
        "Rosemary",
        "Rachel",
        "Ruby",
        "Rebecca",
        "Regina",
        "Rose",
        "Roberta",
    ],
    "s": [
        "Sophia",
        "Serena",
        "Sierra",
        "Susan",
        "Sharon",
        "Stephanie",
        "Sandra",
        "Sheila",
        "Sofia",
        "Sally",
        "Stacey",
        "Samantha",
        "Sarah",
        "Stella",
        "Scarlett",
    ],
    "t": [
        "Thalia",
        "Tina",
        "Tracy",
        "Tiffany",
        "Toni",
        "Trisha",
        "Trinity",
        "Taylor",
        "Theresa",
        "Tessa",
        "Tammy",
        "Tara",
        "Tiana",
        "Tanya",
        "Tasha",
    ],
    "u": ["Ursula", "Ursa", "Ulani", "Unity", "Uma"],
    "v": ["Victoria", "Vanessa", "Vivian", "Valerie", "Veronica", "Violet", "Virginia"],
    "w": ["Wilma", "Willow", "Wanda", "Wren", "Whitney", "Winter", "Wendy"],
    "x": ["Xia", "Xandra", "Xena", "Xochitl", "Xiomara"],
    "y": ["Yuna", "Yvonne", "Yvette", "Yareli", "Yara"],
    "z": ["Zelda", "Zinnia", "Zaria", "Zara", "Zoe"],
}

while True:
    letter = input("Enter a letter: ").lower()
    if letter not in names:
        print("No names found for that letter. Please try another.")
        continue

    name_list = names[letter]
    used_names = set()

    while True:
        if not name_list:
            print("No more names for this letter. Please choose another.")
            break

        name = name_list.pop(0)
        if name not in used_names:
            print(f"Name suggestion: {name}", end="")
            response = input(" (Yes/No)? ").lower()
            if response == "yes":
                print("\nWonderful!")
                exit()
            else:
                used_names.add(name)
